[build]
  publish = "startuphunt/dist"
  command = "cd startuphunt && npm install && npm run build"

# Production environment (main branch)
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# Development environment (dev branch)  
[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "development" }

# Branch deploy contexts
[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "development" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20" 